apiVersion: resources.azapi.m.upbound.io/v1beta1
kind: UpdateResource
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta1/updateresource
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    body:
      properties:
        inboundNatRules:
        - properties:
            idleTimeoutInMinutes: 15
    resourceId: ${azurerm_lb.example.id}
    type: Microsoft.Network/loadBalancers@2021-03-01
