apiVersion: resources.azapi.m.upbound.io/v1beta1
kind: Resource
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta1/resource
  labels:
    testing.upbound.io/example-name: example-container-registry
  name: uptest-example-resource-group-cr
  namespace: upbound-system
spec:
  forProvider:
    body: {}
    parentId: /subscriptions/${data.subscription_id}
    location: West Europe
    name: uptest-example-resource-group-cr
    type: "Microsoft.Resources/resourceGroups@2021-04-01"
---
apiVersion: resources.azapi.m.upbound.io/v1beta1
kind: Resource
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta1/resource
  labels:
    testing.upbound.io/example-name: example-container-registry
  name: example-container-registry
  namespace: upbound-system
spec:
  forProvider:
    body:
      sku:
        name: "Standard"
      properties:
        adminUserEnabled: true
    identity:
      - type: SystemAssigned
    location: West Europe
    name: registrytestupbound
    parentId: /subscriptions/${data.subscription_id}/resourceGroups/uptest-example-resource-group-cr
    responseExportValues:
    - properties.loginServer
    - properties.policies.quarantinePolicy.status
    tags:
      Key: Value
    type: Microsoft.ContainerRegistry/registries@2020-11-01-preview
