apiVersion: resources.azapi.upbound.io/v1beta2
kind: DataPlaneResource
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta2/dataplaneresource
  labels:
    testing.upbound.io/example-name: example-dataset
  name: example-dataset
spec:
  forProvider:
    body:
      properties:
        type: AzureBlob
        typeProperties:
          folderPath:
            value: "@dataset().MyFolderPath"
            type: Expression
          fileName:
            value: "@dataset().MyFileName"
            type: Expression
          format:
            type: TextFormat
        parameters:
          MyFolderPath:
            type: String
          MyFileName:
            type: String
    name: example-dataset
    parentId: uptestexamplesynapse.dev.azuresynapse.net
    type: Microsoft.Synapse/workspaces/datasets@2020-12-01
---
apiVersion: resources.azapi.upbound.io/v1beta2
kind: Resource
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta2/dataplaneresource
  labels:
    testing.upbound.io/example-name: example-dataset
  name: uptest-example-resource-group-synapse
spec:
  forProvider:
    body: {}
    parentId: /subscriptions/${data.subscription_id}
    location: West Europe
    name: uptest-example-resource-group-synapse
    type: "Microsoft.Resources/resourceGroups@2020-06-01"
---
apiVersion: resources.azapi.upbound.io/v1beta2
kind: Resource
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta2/dataplaneresource
  labels:
    testing.upbound.io/example-name: example-dataset
  name: uptest-example-adls-synapse
spec:
  forProvider:
    body:
      kind: StorageV2
      properties:
        accessTier: Hot
        isHnsEnabled: true
        minimumTlsVersion: TLS1_2
        supportsHttpsTrafficOnly: true
      sku:
        name: Standard_LRS
    location: West Europe
    name: uptestexampleadls
    parentId: /subscriptions/${data.subscription_id}/resourceGroups/uptest-example-resource-group-synapse
    type: Microsoft.Storage/storageAccounts@2022-09-01
---
apiVersion: resources.azapi.upbound.io/v1beta2
kind: Resource
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta2/dataplaneresource
  labels:
    testing.upbound.io/example-name: example-dataset
  name: uptest-example-adls-filesystem
spec:
  forProvider:
    body: {}
    name: uptestexamplefs
    parentId: /subscriptions/${data.subscription_id}/resourceGroups/uptest-example-resource-group-synapse/providers/Microsoft.Storage/storageAccounts/uptestexampleadls/blobServices/default
    type: Microsoft.Storage/storageAccounts/blobServices/containers@2022-09-01
---
apiVersion: resources.azapi.upbound.io/v1beta2
kind: Resource
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta2/dataplaneresource
  labels:
    testing.upbound.io/example-name: example-dataset
  name: uptest-example-synapse-workspace
spec:
  forProvider:
    body:
      properties:
        defaultDataLakeStorage:
          accountUrl: https://uptestexampleadls.dfs.core.windows.net
          filesystem: uptestexamplefs
        publicNetworkAccess: Enabled
        sqlAdministratorLogin: sqladminuser
        sqlAdministratorLoginPassword: P@ssw0rd1234!
    identity:
      - type: SystemAssigned
    location: West Europe
    name: uptestexamplesynapse
    parentId: /subscriptions/${data.subscription_id}/resourceGroups/uptest-example-resource-group-synapse
    responseExportValues:
    - properties.connectivityEndpoints.dev
    type: Microsoft.Synapse/workspaces@2021-06-01
---
apiVersion: resources.azapi.upbound.io/v1beta2
kind: Resource
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta2/dataplaneresource
  labels:
    testing.upbound.io/example-name: example-dataset
  name: uptest-example-synapse-firewall-rule
spec:
  forProvider:
    body:
      properties:
        startIpAddress: "0.0.0.0"
        endIpAddress: "255.255.255.255"
    name: AllowAll
    parentId: /subscriptions/${data.subscription_id}/resourceGroups/uptest-example-resource-group-synapse/providers/Microsoft.Synapse/workspaces/uptestexamplesynapse
    type: Microsoft.Synapse/workspaces/firewallRules@2021-06-01
