apiVersion: resources.azapi.upbound.io/v1beta2
kind: Resource
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta2/resourceaction
  labels:
    testing.upbound.io/example-name: example-storage-regeneratekey
  name: uptest-example-resource-group-sa
spec:
  forProvider:
    body: {}
    parentId: /subscriptions/${data.subscription_id}
    location: West Europe
    name: uptest-example-resource-group-sa
    type: "Microsoft.Resources/resourceGroups@2020-06-01"
---
apiVersion: resources.azapi.upbound.io/v1beta2
kind: Resource
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta2/resourceaction
  labels:
    testing.upbound.io/example-name: example-storage-regeneratekey
  name: uptest-example-storage-account-sa
spec:
  forProvider:
    body:
      kind: StorageV2
      properties:
        accessTier: Hot
        minimumTlsVersion: TLS1_2
        supportsHttpsTrafficOnly: true
      sku:
        name: Standard_LRS
    location: West Europe
    name: uptestexamplesa
    parentId: /subscriptions/${data.subscription_id}/resourceGroups/uptest-example-resource-group-sa
    type: Microsoft.Storage/storageAccounts@2022-09-01
---
apiVersion: resources.azapi.upbound.io/v1beta2
kind: ResourceAction
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta2/resourceaction
  labels:
    testing.upbound.io/example-name: example-storage-regeneratekey
  name: example-regenerate-storage-key
spec:
  forProvider:
    action: regenerateKey
    body:
      keyName: key1
    resourceId: /subscriptions/${data.subscription_id}/resourceGroups/uptest-example-resource-group-sa/providers/Microsoft.Storage/storageAccounts/uptestexamplesa
    responseExportValues:
    - keys
    type: Microsoft.Storage/storageAccounts@2022-09-01
