apiVersion: resources.azapi.upbound.io/v1beta1
kind: Resource
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta1/dataplaneresource
  labels:
    testing.upbound.io/example-name: example-purview-collection
  name: uptest-example-resource-group-purview
spec:
  forProvider:
    body: "{}"
    parentId: /subscriptions/${data.subscription_id}
    location: West US
    name: uptest-example-resource-group-purview
    type: "Microsoft.Resources/resourceGroups@2021-04-01"
---
apiVersion: resources.azapi.upbound.io/v1beta1
kind: Resource
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta1/dataplaneresource
  labels:
    testing.upbound.io/example-name: example-purview-collection
  name: uptest-example-purview-account
spec:
  forProvider:
    body: |-
      {
        "properties": {
          "publicNetworkAccess": "Enabled"
        }
      }
    identity:
      - type: SystemAssigned
        identityIds: []
    responseExportValues: ["*"]
    parentId: /subscriptions/${data.subscription_id}/resourceGroups/uptest-example-resource-group-purview
    location: West US
    name: uptestexamplepurview
    type: "Microsoft.Purview/accounts@2021-12-01"
---
apiVersion: resources.azapi.upbound.io/v1beta1
kind: DataPlaneResource
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta1/dataplaneresource
  labels:
    testing.upbound.io/example-name: example-purview-collection
  name: uptest-example-purview-collection
spec:
  forProvider:
    body: |-
      {
        "friendlyName": "UptestExample"
      }
    name: defaultResourceSetRuleConfig
    parentId: uptestexamplepurview.purview.azure.com
    type: "Microsoft.Purview/accounts/Account/collections@2019-11-01-preview"
