name: Azure/terraform-provider-azapi
resources:
    azapi_data_plane_resource:
        subCategory: ""
        description: Manages a Azure data plane resource
        name: azapi_data_plane_resource
        title: azapi_data_plane_resource
        examples:
            - name: dataset
              manifest: |-
                {
                  "body": "${jsonencode({\n    properties = {\n      type = \"AzureBlob\",\n      typeProperties = {\n        folderPath = {\n          value = \"@dataset().MyFolderPath\"\n          type  = \"Expression\"\n        }\n        fileName = {\n          value = \"@dataset().MyFileName\"\n          type  = \"Expression\"\n        }\n        format = {\n          type = \"TextFormat\"\n        }\n      }\n      parameters = {\n        MyFolderPath = {\n          type = \"String\"\n        }\n        MyFileName = {\n          type = \"String\"\n        }\n      }\n    }\n  })}",
                  "name": "example-dataset",
                  "parent_id": "${trimprefix(data.azurerm_synapse_workspace.example.connectivity_endpoints.dev, \"https://\")}",
                  "type": "Microsoft.Synapse/workspaces/datasets@2020-12-01"
                }
        argumentDocs:
            body: '- (Required) A JSON object that contains the request body used to create and update data plane resource.'
            id: '- The ID of the azure resource.'
            ignore_casing: '- (Optional) Whether ignore incorrect casing returned in body to suppress plan-diff. Defaults to false.'
            ignore_missing_property: '- (Optional) Whether ignore not returned properties like credentials in body to suppress plan-diff. Defaults to true.'
            locks: '- (Optional) A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.'
            name: '- (Required) Specifies the name of the azure resource. Changing this forces a new resource to be created.'
            output: '- The output json containing the properties specified in response_export_values. Here''re some examples to decode json and extract the value.'
            parent_id: '- (Required) The ID of the azure resource in which this resource is created. Changing this forces a new resource to be created.'
            response_export_values: |-
                - (Optional) A list of path that needs to be exported from response body.
                Setting it to ["*"] will export the full response body.
                Here's an example. If it sets to ["properties.loginServer", "properties.policies.quarantinePolicy.status"], it will set the following json to computed property output.
            timeouts.create: '- (Defaults to 30 minutes) Used when creating the azure resource.'
            timeouts.delete: '- (Defaults to 30 minutes) Used when deleting the azure resource.'
            timeouts.read: '- (Defaults to 5 minutes) Used when retrieving the azure resource.'
            type: '- (Required) It is in a format like <resource-type>@<api-version>. <api-version> is version of the API used to manage this azure data plane resource.'
        importStatements: []
    azapi_resource:
        subCategory: ""
        description: Manages a Azure resource
        name: azapi_resource
        title: azapi_resource
        examples:
            - name: example
              manifest: |-
                {
                  "body": "${jsonencode({\n    sku = {\n      name = \"Standard\"\n    }\n    properties = {\n      adminUserEnabled = true\n    }\n  })}",
                  "identity": [
                    {
                      "identity_ids": [
                        "${azurerm_user_assigned_identity.example.id}"
                      ],
                      "type": "SystemAssigned, UserAssigned"
                    }
                  ],
                  "location": "${azurerm_resource_group.example.location}",
                  "name": "registry1",
                  "parent_id": "${azurerm_resource_group.example.id}",
                  "response_export_values": [
                    "properties.loginServer",
                    "properties.policies.quarantinePolicy.status"
                  ],
                  "tags": {
                    "Key": "Value"
                  },
                  "type": "Microsoft.ContainerRegistry/registries@2020-11-01-preview"
                }
              references:
                location: azurerm_resource_group.example.location
                parent_id: azurerm_resource_group.example.id
              dependencies:
                azurerm_resource_group.example: |-
                    {
                      "location": "west europe",
                      "name": "example-rg"
                    }
                azurerm_user_assigned_identity.example: |-
                    {
                      "location": "${azurerm_resource_group.example.location}",
                      "name": "example",
                      "resource_group_name": "${azurerm_resource_group.example.name}"
                    }
        argumentDocs:
            Microsoft.Resources/resourceGroups: ', the parent_id could be omitted, it defaults to subscription ID specified in provider or the default subscription(You could check the default subscription by azure cli command: az account show).'
            body: '- (Required) A JSON object that contains the request body used to create and update azure resource.'
            id: '- The ID of the azure resource.'
            identity: '- (Optional) A identity block as defined below.'
            identity.identity_ids: '- (Optional) A list of User Managed Identity ID''s which should be assigned to the azure resource.'
            identity.principal_id: '- The Principal ID for the Service Principal associated with the Managed Service Identity of this azure resource.'
            identity.tenant_id: '- The Tenant ID for the Service Principal associated with the Managed Service Identity of this azure resource.'
            identity.type: '- (Required) The Type of Identity which should be used for this azure resource. Possible values are SystemAssigned, UserAssigned and SystemAssigned,UserAssigned.'
            ignore_body_changes: '- (Optional) A list of properties that should be ignored when comparing the body with its current state.'
            ignore_casing: '- (Optional) Whether ignore incorrect casing returned in body to suppress plan-diff. Defaults to false.'
            ignore_missing_property: '- (Optional) Whether ignore not returned properties like credentials in body to suppress plan-diff. Defaults to true.'
            location: '- (Optional) The Azure Region where the azure resource should exist.'
            locks: '- (Optional) A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.'
            name: '- (Required) Specifies the name of the azure resource. Changing this forces a new resource to be created.'
            output: '- The output json containing the properties specified in response_export_values. Here''re some examples to decode json and extract the value.'
            parent_id: '- (Required) The ID of the azure resource in which this resource is created. Changing this forces a new resource to be created. It supports different kinds of deployment scope for top level resources:'
            removing_special_chars: '- (Optional) Whether to remove special characters in resource name. Defaults to false.'
            response_export_values: |-
                - (Optional) A list of path that needs to be exported from response body.
                Setting it to ["*"] will export the full response body.
                Here's an example. If it sets to ["properties.loginServer", "properties.policies.quarantinePolicy.status"], it will set the following json to computed property output.
            schema_validation_enabled: '- (Optional) Whether enabled the validation on type and body with embedded schema. Defaults to true.'
            tags: '- (Optional) A mapping of tags which should be assigned to the azure resource.'
            timeouts.create: '- (Defaults to 30 minutes) Used when creating the azure resource.'
            timeouts.delete: '- (Defaults to 30 minutes) Used when deleting the azure resource.'
            timeouts.read: '- (Defaults to 5 minutes) Used when retrieving the azure resource.'
            type: |-
                - (Required) It is in a format like <resource-type>@<api-version>. <resource-type> is the Azure resource type, for example, Microsoft.Storage/storageAccounts.
                <api-version> is version of the API used to manage this azure resource.
        importStatements:
            - terraform import azapi_resource.example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resGroup1/providers/Microsoft.MachineLearningServices/workspaces/workspace1/computes/cluster1
            - terraform import azapi_resource.example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resGroup1/providers/Microsoft.MachineLearningServices/workspaces/workspace1/computes/cluster1?api-version=2021-07-01
    azapi_resource_action:
        subCategory: ""
        description: Perform resource action which changes an existing resource's state
        name: azapi_resource_action
        title: azapi_resource_action
        examples:
            - name: start
              manifest: |-
                {
                  "action": "start",
                  "count": "${var.enabled ? 1 : 0}",
                  "resource_id": "${azurerm_spring_cloud_service.test.id}",
                  "response_export_values": [
                    "*"
                  ],
                  "type": "Microsoft.AppPlatform/Spring@2022-05-01-preview"
                }
              references:
                resource_id: azurerm_spring_cloud_service.test.id
              dependencies:
                azurerm_resource_group.example: |-
                    {
                      "location": "west europe",
                      "name": "example-rg"
                    }
                azurerm_spring_cloud_service.test: |-
                    {
                      "location": "${azurerm_resource_group.test.location}",
                      "name": "example-spring",
                      "resource_group_name": "${azurerm_resource_group.test.name}",
                      "sku_name": "S0"
                    }
            - name: stop
              manifest: |-
                {
                  "action": "stop",
                  "count": "${var.enabled ? 0 : 1}",
                  "resource_id": "${azurerm_spring_cloud_service.test.id}",
                  "response_export_values": [
                    "*"
                  ],
                  "type": "Microsoft.AppPlatform/Spring@2022-05-01-preview"
                }
              references:
                resource_id: azurerm_spring_cloud_service.test.id
              dependencies:
                azurerm_resource_group.example: |-
                    {
                      "location": "west europe",
                      "name": "example-rg"
                    }
                azurerm_spring_cloud_service.test: |-
                    {
                      "location": "${azurerm_resource_group.test.location}",
                      "name": "example-spring",
                      "resource_group_name": "${azurerm_resource_group.test.name}",
                      "sku_name": "S0"
                    }
            - name: test
              manifest: |-
                {
                  "action": "register",
                  "method": "POST",
                  "resource_id": "/subscriptions/${data.azurerm_client_config.current.subscription_id}/providers/Microsoft.Compute",
                  "type": "Microsoft.Resources/providers@2021-04-01"
                }
        argumentDocs:
            action: '- (Optional) The name of the resource action. It''s also possible to make Http requests towards the resource ID if leave this field empty.'
            body: '- (Optional) A JSON object that contains the request body.'
            id: '- The ID of the azure resource action.'
            locks: '- (Optional) A list of ARM resource IDs which are used to avoid modify azapi resources at the same time.'
            method: '- (Optional) Specifies the Http method of the azure resource action. Allowed values are POST, PATCH, PUT and DELETE. Defaults to POST.'
            output: '- The output json containing the properties specified in response_export_values. Here are some examples to decode json and extract the value.'
            resource_id: '- (Required) The ID of an existing azure source.'
            response_export_values: |-
                - (Optional) A list of path that needs to be exported from response body.
                Setting it to ["*"] will export the full response body.
                Here's an example. If it sets to ["keys"], it will set the following json to computed property output.
            timeouts.create: '- (Defaults to 30 minutes) Used when creating the azure resource.'
            timeouts.delete: '- (Defaults to 30 minutes) Used when deleting the azure resource.'
            timeouts.read: '- (Defaults to 5 minutes) Used when retrieving the azure resource.'
            type: |-
                - (Required) It is in a format like <resource-type>@<api-version>. <resource-type> is the Azure resource type, for example, Microsoft.Storage/storageAccounts.
                <api-version> is version of the API used to manage this azure resource.
            when: '- (Optional) When to perform the action, value must be one of: apply, destroy. Default is apply.'
        importStatements: []
    azapi_update_resource:
        subCategory: ""
        description: Manages a subset of an existing azure resource's properties
        name: azapi_update_resource
        title: azapi_update_resource
        examples:
            - name: example
              manifest: |-
                {
                  "body": "${jsonencode({\n    properties = {\n      inboundNatRules = [\n        {\n          properties = {\n            idleTimeoutInMinutes = 15\n          }\n        }\n      ]\n    }\n  })}",
                  "depends_on": [
                    "${azurerm_lb_nat_rule.example}"
                  ],
                  "resource_id": "${azurerm_lb.example.id}",
                  "type": "Microsoft.Network/loadBalancers@2021-03-01"
                }
              references:
                resource_id: azurerm_lb.example.id
              dependencies:
                azurerm_lb.example: |-
                    {
                      "frontend_ip_configuration": [
                        {
                          "name": "PublicIPAddress",
                          "public_ip_address_id": "${azurerm_public_ip.example.id}"
                        }
                      ],
                      "location": "${azurerm_resource_group.example.location}",
                      "name": "example-lb",
                      "resource_group_name": "${azurerm_resource_group.example.name}"
                    }
                azurerm_lb_nat_rule.example: |-
                    {
                      "backend_port": 3389,
                      "frontend_ip_configuration_name": "PublicIPAddress",
                      "frontend_port": 3389,
                      "loadbalancer_id": "${azurerm_lb.example.id}",
                      "name": "RDPAccess",
                      "protocol": "Tcp",
                      "resource_group_name": "${azurerm_resource_group.example.name}"
                    }
                azurerm_public_ip.example: |-
                    {
                      "allocation_method": "Static",
                      "location": "${azurerm_resource_group.example.location}",
                      "name": "example-ip",
                      "resource_group_name": "${azurerm_resource_group.example.name}"
                    }
                azurerm_resource_group.example: |-
                    {
                      "location": "west europe",
                      "name": "example-rg"
                    }
        argumentDocs:
            body: '- (Required) A JSON object that contains the request body used to add on an existing azure resource.'
            id: '- The ID of the azure resource.'
            ignore_body_changes: '- (Optional) A list of properties that should be ignored when comparing the body with its current state.'
            ignore_casing: '- (Optional) Whether ignore incorrect casing returned in body to suppress plan-diff. Defaults to false.'
            ignore_missing_property: '- (Optional) Whether ignore not returned properties like credentials in body to suppress plan-diff. Defaults to true.'
            locks: '- (Optional) A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.'
            name: '- (Optional) Specifies the name of the azure resource. Changing this forces a new resource to be created.'
            output: '- The output json containing the properties specified in response_export_values. Here''re some examples to decode json and extract the value.'
            parent_id: '- (Optional) The ID of the azure resource in which this resource is created. Changing this forces a new resource to be created. It supports different kinds of deployment scope for top level resources:'
            resource_id: '- (Optional) The ID of an existing azure source. Changing this forces a new azure resource to be created.'
            response_export_values: |-
                - (Optional) A list of path that needs to be exported from response body.
                Setting it to ["*"] will export the full response body.
                Here's an example. If it sets to ["properties.loginServer", "properties.policies.quarantinePolicy.status"], it will set the following json to computed property output.
            timeouts.create: '- (Defaults to 30 minutes) Used when creating the azure resource.'
            timeouts.delete: '- (Defaults to 30 minutes) Used when deleting the azure resource.'
            timeouts.read: '- (Defaults to 5 minutes) Used when retrieving the azure resource.'
            type: |-
                - (Required) It is in a format like <resource-type>@<api-version>. <resource-type> is the Azure resource type, for example, Microsoft.Storage/storageAccounts.
                <api-version> is version of the API used to manage this azure resource.
        importStatements: []
