apiVersion: resources.azapi.upbound.io/v1alpha1
kind: Resource
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1alpha1/resource
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    body: |-
      ${jsonencode({
          sku = {
            name = "Standard"
          }
          properties = {
            adminUserEnabled = true
          }
        })}
    location: West Europe
    name: registrytestupbound
    parentId: ${azurerm_resource_group.example.id}
    responseExportValues:
    - properties.loginServer
    - properties.policies.quarantinePolicy.status
    tags:
      Key: Value
    type: Microsoft.ContainerRegistry/registries@2020-11-01-preview
# This resource needs a valid parentId (resource group example id)
