apiVersion: resource.upbound.io/v1alpha1
kind: UpdateResource
metadata:
  annotations:
    meta.upbound.io/example-id: resource/v1alpha1/updateresource
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    body: |-
      ${jsonencode({
          properties = {
            inboundNatRules = [
              {
                properties = {
                  idleTimeoutInMinutes = 15
                }
              }
            ]
          }
        })}
    resourceId: ${azurerm_lb.example.id}
    type: Microsoft.Network/loadBalancers@2021-03-01
