// SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *DataPlaneResource) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Resource) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ResourceAction) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UpdateResource) Hub() {}
