// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type UpdateResourceInitParameters struct {

	// A JSON object that contains the request body used to add on an existing azure resource.
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// A list of properties that should be ignored when comparing the body with its current state.
	IgnoreBodyChanges []*string `json:"ignoreBodyChanges,omitempty" tf:"ignore_body_changes,omitempty"`

	// Whether ignore incorrect casing returned in body to suppress plan-diff. Defaults to false.
	IgnoreCasing *bool `json:"ignoreCasing,omitempty" tf:"ignore_casing,omitempty"`

	// Whether ignore not returned properties like credentials in body to suppress plan-diff. Defaults to true.
	IgnoreMissingProperty *bool `json:"ignoreMissingProperty,omitempty" tf:"ignore_missing_property,omitempty"`

	// A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
	Locks []*string `json:"locks,omitempty" tf:"locks,omitempty"`

	// Specifies the name of the azure resource. Changing this forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the azure resource in which this resource is created. Changing this forces a new resource to be created. It supports different kinds of deployment scope for top level resources:
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// The ID of an existing azure source. Changing this forces a new azure resource to be created.
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// A list of path that needs to be exported from response body.
	// Setting it to ["*"] will export the full response body.
	// Here's an example. If it sets to ["properties.loginServer", "properties.policies.quarantinePolicy.status"], it will set the following json to computed property output.
	ResponseExportValues []*string `json:"responseExportValues,omitempty" tf:"response_export_values,omitempty"`

	// It is in a format like <resource-type>@<api-version>. <resource-type> is the Azure resource type, for example, Microsoft.Storage/storageAccounts.
	// <api-version> is version of the API used to manage this azure resource.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type UpdateResourceObservation struct {

	// A JSON object that contains the request body used to add on an existing azure resource.
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// The ID of the azure resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A list of properties that should be ignored when comparing the body with its current state.
	IgnoreBodyChanges []*string `json:"ignoreBodyChanges,omitempty" tf:"ignore_body_changes,omitempty"`

	// Whether ignore incorrect casing returned in body to suppress plan-diff. Defaults to false.
	IgnoreCasing *bool `json:"ignoreCasing,omitempty" tf:"ignore_casing,omitempty"`

	// Whether ignore not returned properties like credentials in body to suppress plan-diff. Defaults to true.
	IgnoreMissingProperty *bool `json:"ignoreMissingProperty,omitempty" tf:"ignore_missing_property,omitempty"`

	// A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
	Locks []*string `json:"locks,omitempty" tf:"locks,omitempty"`

	// Specifies the name of the azure resource. Changing this forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The output json containing the properties specified in response_export_values. Here're some examples to decode json and extract the value.
	Output *string `json:"output,omitempty" tf:"output,omitempty"`

	// The ID of the azure resource in which this resource is created. Changing this forces a new resource to be created. It supports different kinds of deployment scope for top level resources:
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// The ID of an existing azure source. Changing this forces a new azure resource to be created.
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// A list of path that needs to be exported from response body.
	// Setting it to ["*"] will export the full response body.
	// Here's an example. If it sets to ["properties.loginServer", "properties.policies.quarantinePolicy.status"], it will set the following json to computed property output.
	ResponseExportValues []*string `json:"responseExportValues,omitempty" tf:"response_export_values,omitempty"`

	// It is in a format like <resource-type>@<api-version>. <resource-type> is the Azure resource type, for example, Microsoft.Storage/storageAccounts.
	// <api-version> is version of the API used to manage this azure resource.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type UpdateResourceParameters struct {

	// A JSON object that contains the request body used to add on an existing azure resource.
	// +kubebuilder:validation:Optional
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// A list of properties that should be ignored when comparing the body with its current state.
	// +kubebuilder:validation:Optional
	IgnoreBodyChanges []*string `json:"ignoreBodyChanges,omitempty" tf:"ignore_body_changes,omitempty"`

	// Whether ignore incorrect casing returned in body to suppress plan-diff. Defaults to false.
	// +kubebuilder:validation:Optional
	IgnoreCasing *bool `json:"ignoreCasing,omitempty" tf:"ignore_casing,omitempty"`

	// Whether ignore not returned properties like credentials in body to suppress plan-diff. Defaults to true.
	// +kubebuilder:validation:Optional
	IgnoreMissingProperty *bool `json:"ignoreMissingProperty,omitempty" tf:"ignore_missing_property,omitempty"`

	// A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
	// +kubebuilder:validation:Optional
	Locks []*string `json:"locks,omitempty" tf:"locks,omitempty"`

	// Specifies the name of the azure resource. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the azure resource in which this resource is created. Changing this forces a new resource to be created. It supports different kinds of deployment scope for top level resources:
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// The ID of an existing azure source. Changing this forces a new azure resource to be created.
	// +kubebuilder:validation:Optional
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// A list of path that needs to be exported from response body.
	// Setting it to ["*"] will export the full response body.
	// Here's an example. If it sets to ["properties.loginServer", "properties.policies.quarantinePolicy.status"], it will set the following json to computed property output.
	// +kubebuilder:validation:Optional
	ResponseExportValues []*string `json:"responseExportValues,omitempty" tf:"response_export_values,omitempty"`

	// It is in a format like <resource-type>@<api-version>. <resource-type> is the Azure resource type, for example, Microsoft.Storage/storageAccounts.
	// <api-version> is version of the API used to manage this azure resource.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// UpdateResourceSpec defines the desired state of UpdateResource
type UpdateResourceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UpdateResourceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UpdateResourceInitParameters `json:"initProvider,omitempty"`
}

// UpdateResourceStatus defines the observed state of UpdateResource.
type UpdateResourceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UpdateResourceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UpdateResource is the Schema for the UpdateResources API. Manages a subset of an existing azure resource's properties
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azapi}
type UpdateResource struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   UpdateResourceSpec   `json:"spec"`
	Status UpdateResourceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UpdateResourceList contains a list of UpdateResources
type UpdateResourceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UpdateResource `json:"items"`
}

// Repository type metadata.
var (
	UpdateResource_Kind             = "UpdateResource"
	UpdateResource_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UpdateResource_Kind}.String()
	UpdateResource_KindAPIVersion   = UpdateResource_Kind + "." + CRDGroupVersion.String()
	UpdateResource_GroupVersionKind = CRDGroupVersion.WithKind(UpdateResource_Kind)
)

func init() {
	SchemeBuilder.Register(&UpdateResource{}, &UpdateResourceList{})
}
